### ISSUE TITLE
Crashes companion when using version 2.9.2 of OpenLP

### ISSUE THREAD

**Issue by chippieuk** [bitfocus/companion-module-openlp-http#8]
I thought I'd test out the latest beta of OpenLP (v2.9.2) and found the unexpected result of it crashing companion. The web interface shows the 'Houston we have a problem' message as soon as OpenLP is opened. Closing OpenLP then re-starting comapnion resolves this, as does disabling the OpenLP plugin on companion.

**Comment by jendamozna** [comment]
It doesnt seem to be related to companion-module-openlp-http. OpenLP 2.9.2 is still in beta. GET /api/poll currently returns "null" instead of json response, which causes companion crash. 

Rereported to openlp: https://gitlab.com/openlp/openlp/-/issues/890

**Comment by trb143** [comment]
The API will be changing and moving to WebSockets.  We will be removing the POLL API in future releases.

**Comment by jendamozna** [comment]
Fixed in 2.9.3
