### ISSUE TITLE
Module for Openlp v3

### ISSUE THREAD

**Issue by jendamozna** [bitfocus/companion-module-openlp-http#9]
Hi, whats the process of publishing new version of companion module for openlp v3?

ive already created some
https://github.com/jendamozna/companion-module-openlp3-remote

Feel free to download to companion/module-local-dev and test...

Should it be merged to current module or requested new one?

**Comment by Gartom** [comment]
As some of us are still using the old OpenLP version, I would say that any updates to make the openlp module compatible with OpenLP v3 would need to be backwards compatible. 
As OpenLP v3 is not out of beta, our church will not update to v3 yet.

**Comment by jendamozna** [comment]
fixed in https://github.com/bitfocus/companion-module-openlp-http/pull/11
